### ISSUE TITLE
Не отображается режим нагревателя

### ISSUE THREAD

**Issue by GZ-3** [RealLord/tion_home_assistant#10]
В карточке бризера tion 4s нет возможности включить нагреватель, в самом entity доступно только hvac_modes: off, fan_only. Однако нагреватель можно включить через:
```
action: climate.set_hvac_mode
data:
  hvac_mode: heat
target:
  entity_id: climate.breezer_dom_bed
```
соответственно когда нагреватель включён не отображается в tile какой режим включён.

Также если полностью выключить бризер, то это не отображается в home assistant.
Неправильно описан swing mode: vertical - с улицы, both - из комнаты.
