### ISSUE TITLE
Не получается управлять бризером после включения режима auto

### ISSUE THREAD

**Issue by Daemon256** [RealLord/tion_home_assistant#4]
Tion Breezer 3S 1
В последней версии наконец заработал режим auto и даже работает как надо, однако теперь никак из него нельзя выйти :)
Пробовал разные варианты (с закоментирование и раскоментированием последней части кода и ручным запуском), ничего не срабатывает:

```


- alias: control_breezer_nigth_0_15
  trigger:
    platform: time
    at: "00:15:00"
  condition:
    - condition: state # если свет включен
      entity_id: switch.osveshchenie_ulitsy
      state: 'on' 
  action:
# выключаем бризер  
      - service: climate.set_hvac_mode
        entity_id: climate.tion_breezer_3s_1
        data:
           hvac_mode: "off"
#   - service: climate.set_fan_mode
#      entity_id: climate.tion_breezer_3s_1
#      data:
#         fan_mode: "off"
``` 

И что работало до включения auto, тоже перестало работать (выключить можно только через приложение или сайт) :

```

- alias: control_breezer_nigth_2_winter
  id: control_breezer_nigth_2_winter
  trigger:
    platform: time
    at: "02:10:00"
  condition:
    - condition: state # если свет включен
      entity_id: switch.osveshchenie_ulitsy
      state: 'on' 
    - condition: numeric_state
      entity_id: sensor.bmp180_temperature
      below: 10
  action:
  - service: climate.set_fan_mode
    entity_id: climate.tion_breezer_3s_1
    data:
      fan_mode: "1"
  - service: climate.set_hvac_mode
    entity_id: climate.tion_breezer_3s_1
    data:
      hvac_mode: "heat"
  - service: climate.set_swing_mode
    entity_id: climate.tion_breezer_3s_1
    data:
      swing_mode: "horizontal"    

``` 

В общем происходит полное игнорирование команд пока он в режиме auto ( о чём в принципе и написано в приложении, что пока  включен auto режим, управлять бризером нельзя, но как его отключить)?
